CREATE OR REPLACE EDITIONABLE FUNCTION "WMS"."F_ENDERCO_ABS" (PNENDORG IN NUMBER, PNENDDES IN NUMBER, PNTIPO IN VARCHAR2, OPCAO NUMBER)
  RETURN VARCHAR2 IS
  ENDERCO_ORIGEM VARCHAR2(100);
  ENDERCO_DESTINO VARCHAR2(100);

BEGIN

  IF PNTIPO = 'P' THEN

select A.RUA || '.' || A.PREDIO || '.' || A.APARTAMENTO || '.' || A.SALA INTO ENDERCO_ORIGEM
  from WMS.ENDERECO A
 inner join WMS.PALETE B
    on B.ENDERECO_ID = A.ID
 inner join WMS.PRODUTO_EMBALAGEM C
    on C.ID = A.EMBALAGEM_ID
    inner join WMS.PRODUTO_EMBALAGEM C1
    on C1.ID = B.EMBALAGEM_ID
    inner join WMS.PRODUTO D
    on D.ID = A.PRODUTO_ID
    and D.ID = C.PRODUTO_ID
    and D.ID = C1.PRODUTO_ID
    WHERE A.ID =  PNENDORG;
        
    SELECT PNENDDES INTO ENDERCO_DESTINO FROM DUAL;
    IF OPCAO = 1 THEN
    RETURN ENDERCO_ORIGEM;
    END IF;
    IF OPCAO = 2 THEN
    RETURN ENDERCO_DESTINO;
    END IF;
  END IF;

   IF PNTIPO IN ( 'R','D' ) THEN

select A.RUA || '.' || A.PREDIO || '.' || A.APARTAMENTO || '.' || A.SALA INTO ENDERCO_ORIGEM
  from WMS.ENDERECO A
 inner join WMS.PALETE B
    on B.ENDERECO_ID = A.ID
 inner join WMS.PRODUTO_EMBALAGEM C
    on C.ID = A.EMBALAGEM_ID
    inner join WMS.PRODUTO_EMBALAGEM C1
    on C1.ID = B.EMBALAGEM_ID
    inner join WMS.PRODUTO D
    on D.ID = A.PRODUTO_ID
    and D.ID = C.PRODUTO_ID
    and D.ID = C1.PRODUTO_ID
    WHERE A.ID =  PNENDORG
;
select A.RUA || '.' || A.PREDIO || '.' || A.APARTAMENTO || '.' || A.SALA INTO ENDERCO_DESTINO
  from WMS.ENDERECO A
 inner join WMS.PALETE B
    on B.ENDERECO_ID = A.ID
 inner join WMS.PRODUTO_EMBALAGEM C
    on C.ID = A.EMBALAGEM_ID
    inner join WMS.PRODUTO_EMBALAGEM C1
    on C1.ID = B.EMBALAGEM_ID
    inner join WMS.PRODUTO D
    on D.ID = A.PRODUTO_ID
    and D.ID = C.PRODUTO_ID
    and D.ID = C1.PRODUTO_ID
    WHERE A.ID =  PNENDDES;

    IF OPCAO = 1 THEN
    RETURN ENDERCO_ORIGEM;
    END IF;
    IF OPCAO = 2 THEN
    RETURN ENDERCO_DESTINO;
    END IF;
  END IF;

END;
/