CREATE TABLE "WMS"."PRINT_ERROR" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"CARGA_ID" NUMBER NOT NULL ENABLE, 
	"LOTE" NUMBER, 
	"INFO" VARCHAR2(4000), 
	"ALERT_STATUS" NUMBER, 
	"CREATED" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	"UPDATED" DATE NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	 CONSTRAINT "PRINT_ERROR_ALERT_STATUS_CC" CHECK (alert_status in (0,1)) ENABLE, 
	 CONSTRAINT "PRINT_ERROR_ID_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;