CREATE TABLE "WMS"."PRODUTO_EMBALAGEM" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"LS" VARCHAR2(3), 
	"PRODUTO_ID" NUMBER, 
	"EMB" VARCHAR2(2), 
	"QTD_EMB" NUMBER, 
	"PESO_BRUTO" NUMBER, 
	"PESO_LIQUIDO" NUMBER, 
	"ALTURA" NUMBER, 
	"LARGURA" NUMBER, 
	"PROFUNDIDADE" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "PRODUTO_EMBALAGEM_ID_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;