CREATE TABLE "WMS"."TIPO_ARMAZENAGEM" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NOME" VARCHAR2(100) NOT NULL ENABLE, 
	"STATUS" NUMBER, 
	 CONSTRAINT "TIPO_ARMAZENAGEM_STATUS_CC" CHECK (status in (0,1)) ENABLE, 
	 CONSTRAINT "TIPO_ARMAZENAGEM_ID_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;