CREATE TABLE "WMS"."ENDERECO" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"RUA" VARCHAR2(3) NOT NULL ENABLE, 
	"PREDIO" NUMBER NOT NULL ENABLE, 
	"APARTAMENTO" NUMBER NOT NULL ENABLE, 
	"SALA" NUMBER NOT NULL ENABLE, 
	"PULMAO" NUMBER, 
	"PRODUTO_ID" NUMBER, 
	"QTD_ATUAL" NUMBER, 
	"STATUS" VARCHAR2(60), 
	"TIPO_ID" NUMBER, 
	"ESPECIE_ID" NUMBER, 
	"TERREO" NUMBER, 
	"EMBALAGEM_ID" NUMBER, 
	"EXPEDICAO" NUMBER, 
	"TIPO_REPOSICAO" VARCHAR2(1), 
	"TIPO_ESPECIAL" NUMBER, 
	"GERAR_REPOSICAO" NUMBER, 
	"VIRTUAL" NUMBER, 
	 CONSTRAINT "ENDERECO_PULMAO_CC" CHECK (pulmao in (0,1)) ENABLE, 
	 CONSTRAINT "ENDERECO_ID_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "ENDERECO_TERREO_CC" CHECK (terreo in (0,1)) ENABLE, 
	 CONSTRAINT "ENDERECO_EXPEDICAO_CC" CHECK (expedicao in (0,1)) ENABLE, 
	 CONSTRAINT "ENDERECO_STATUS_CC" CHECK (status in (0,1)) ENABLE, 
	 CONSTRAINT "ENDERECO_TIPO_ID_FK" FOREIGN KEY ("TIPO_ID")
	  REFERENCES "WMS"."ENDERECO_TIPO" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "ENDERECO_ESPECIE_ID_FK" FOREIGN KEY ("ESPECIE_ID")
	  REFERENCES "WMS"."ENDERECO_ESPECIE" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "ENDERECO_EMBALAGEM_ID_FK" FOREIGN KEY ("EMBALAGEM_ID")
	  REFERENCES "WMS"."PRODUTO_EMBALAGEM" ("ID") ON DELETE CASCADE ENABLE
   ) ;