CREATE TABLE "WMS"."ENDERECO_VALIDADE" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"ENDERECO_ID" NUMBER, 
	"QTD_ATUAL" NUMBER NOT NULL ENABLE, 
	"DATA_VALIDADE" DATE NOT NULL ENABLE, 
	"DATA_RECEBIMENTO" DATE NOT NULL ENABLE, 
	"SATUS" NUMBER, 
	 CONSTRAINT "ENDERECO_VALIDADE_SATUS_CC" CHECK (satus in (0,1)) ENABLE, 
	 CONSTRAINT "ENDERECO_VALIDADE_ID_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "ENDERECO_VALIDA_ENDERECO_ID_FK" FOREIGN KEY ("ENDERECO_ID")
	  REFERENCES "WMS"."ENDERECO" ("ID") ON DELETE CASCADE ENABLE
   ) ;