CREATE TABLE "WMS"."ERRO_SEPARACAO_ALERTA" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"ERRO_SEPARACAO_ID" NUMBER, 
	"BOX_ID" NUMBER NOT NULL ENABLE, 
	"LOCAL" VARCHAR2(4000), 
	"DONE_PUBLICO" NUMBER, 
	"DONE_PRIVADO" NUMBER, 
	"DONE_ADMIN" NUMBER DEFAULT ON NULL '1' NOT NULL ENABLE, 
	"CREATED" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	"UPDATED" DATE NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	 CONSTRAINT "ERRO_SEPARACAO_DONE_PUBLIC_CC" CHECK (done_publico in (0,1)) ENABLE, 
	 CONSTRAINT "ERRO_SEPARACAO_DONE_PRIVAD_CC" CHECK (done_privado in (0,1)) ENABLE, 
	 CONSTRAINT "ERRO_SEPARACAO_DONE_ADMIN_CC" CHECK (done_admin in (0,1)) ENABLE, 
	 CONSTRAINT "ERRO_SEPARACAO_ALE_ID_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "ERRO_SEPARACA_ERRO_SEPARACA_FK" FOREIGN KEY ("ERRO_SEPARACAO_ID")
	  REFERENCES "WMS"."ERRO_SEPARACAO" ("ID") ON DELETE CASCADE ENABLE
   ) ;