CREATE TABLE "WMS"."TESTE" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"C_NUM" VARCHAR2(4000), 
	"C_VC" VARCHAR2(4000), 
	"C_DATE" DATE, 
	 CONSTRAINT "TESTE_ID_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;