CREATE TABLE "WMS"."PRODUTO_ESPECIE" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"ESPECIE_ID" NUMBER, 
	"EMBALAGEM_ID" NUMBER, 
	"ESTOQUE_MIN" NUMBER, 
	"LASTRO" NUMBER, 
	"ALTURA" NUMBER, 
	"SOBRA" NUMBER, 
	"PRODUTO_ID" NUMBER, 
	"DATA" DATE, 
	 CONSTRAINT "PRODUTO_ESPECIE_ID_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "PRODUTO_ESPECIE_ESPECIE_ID_FK" FOREIGN KEY ("ESPECIE_ID")
	  REFERENCES "WMS"."ENDERECO_ESPECIE" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "PRODUTO_ESPECIE_EMBALAGEM_I_FK" FOREIGN KEY ("EMBALAGEM_ID")
	  REFERENCES "WMS"."PRODUTO_EMBALAGEM" ("ID") ON DELETE CASCADE ENABLE
   ) ;