CREATE TABLE "WMS"."EMBALAGEM_CODIGO" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"EMBALAGEM_ID" NUMBER NOT NULL ENABLE, 
	"CODIGO" VARCHAR2(100) NOT NULL ENABLE, 
	"TIPO" VARCHAR2(1) NOT NULL ENABLE, 
	 CONSTRAINT "EMBALAGEM_CODIG_TIPO_CODIGO_CC" CHECK ("TIPO"='E' OR "TIPO"='D' OR "TIPO"='I' OR "TIPO"='T') DISABLE, 
	 CONSTRAINT "EMBALAGEM_CODIGO_ID_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;