CREATE TABLE "WMS"."PRODUTO" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NOME" VARCHAR2(1000), 
	"ENDERECO_TIPO_ID" NUMBER, 
	"TIPO_ARMAZENAGEM_ID" NUMBER, 
	"DIAS_VALIDADE" NUMBER, 
	"STATUS" NUMBER, 
	"EMBALAGEM_ID" NUMBER, 
	"FORNECEDOR_ID" NUMBER, 
	"REFFABRICANTE" VARCHAR2(61), 
	 CONSTRAINT "PRODUTO_ID_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "PRODUTO_STATUS_CC" CHECK (status in ('0','1')) ENABLE
   ) ;