CREATE TABLE "WMS"."CORTE_LOG" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"CORTE_ID" NUMBER NOT NULL ENABLE, 
	"PESSOA_ID" NUMBER NOT NULL ENABLE, 
	"QTD_EMB" NUMBER, 
	"QTD_PEDIDO" NUMBER, 
	"QTD_DIGITADO" NUMBER, 
	"CREATED" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	"UPDATED" DATE NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	 CONSTRAINT "CORTE_LOG_ID_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;