CREATE TABLE "WMS"."MOVIMENTACAO" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"TIPO" VARCHAR2(1), 
	"ORIGEM_ID" NUMBER, 
	"DESTINO_ID" NUMBER, 
	"STATUS" NUMBER, 
	"EMP_ID" NUMBER, 
	"EMP_START" DATE, 
	"EMP_END" DATE, 
	"ABAST_ID" NUMBER, 
	"ABAST_START" DATE, 
	"ABAST_END" DATE, 
	"LOTE_ID" NUMBER, 
	"QTD" NUMBER, 
	"EMB" VARCHAR2(2), 
	"QTD_EMB" NUMBER, 
	"PALETE_ID" NUMBER, 
	"PRIORIDADE" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "MOVIMENTACAO_CON" CHECK ( "TIPO" in ('A','D','R','P','E')) ENABLE, 
	 CONSTRAINT "MOVIMENTACAO_ID_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "MOVIMENTACAO_EMP_ID_FK" FOREIGN KEY ("EMP_ID")
	  REFERENCES "WMS"."PRODUTIVO" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "MOVIMENTACAO_ABAST_ID_FK" FOREIGN KEY ("ABAST_ID")
	  REFERENCES "WMS"."PRODUTIVO" ("ID") ON DELETE CASCADE ENABLE
   ) ;