CREATE TABLE "WMS"."USUARIO" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"LOGIN" VARCHAR2(20), 
	"NOME" VARCHAR2(100), 
	"SENHA" VARCHAR2(20), 
	"MUDAR_SENHA" NUMBER, 
	"GRUPO_ID" NUMBER, 
	 CONSTRAINT "USUARIO_ID_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "USUARIO_GRUPO_ID_FK" FOREIGN KEY ("GRUPO_ID")
	  REFERENCES "WMS"."GRUPO_ACESSO" ("ID") ON DELETE CASCADE ENABLE
   ) ;