CREATE TABLE "WMS"."PALETE" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"QTD" NUMBER NOT NULL ENABLE, 
	"ENDERECO_ID" NUMBER NOT NULL ENABLE, 
	"EMBALAGEM_ID" NUMBER NOT NULL ENABLE, 
	"STATUS" NUMBER NOT NULL ENABLE, 
	"CONF_ID" NUMBER, 
	"CONF_QTD" NUMBER, 
	"CONF_START" DATE, 
	"CONF_END" DATE, 
	"VALIDADE" DATE, 
	"CARGA_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "PALETE_ID_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;