CREATE TABLE "WMS"."PRODUTIVO_LS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"PRODUTIVO_ID" NUMBER, 
	"LS_ID" NUMBER, 
	"CREATED" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	"UPDATED" DATE NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	 CONSTRAINT "PRODUTIVO_LS_ID_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "PRODUTIVO_LS_PRODUTIVO_ID_FK" FOREIGN KEY ("PRODUTIVO_ID")
	  REFERENCES "WMS"."PRODUTIVO" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "PRODUTIVO_LS_LS_ID_FK" FOREIGN KEY ("LS_ID")
	  REFERENCES "WMS"."LINHADESEPARACAO" ("ID") ON DELETE CASCADE ENABLE
   ) ;