CREATE TABLE "WMS"."ENDERECO_TIPO" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NOME" VARCHAR2(100) NOT NULL ENABLE, 
	"ALTURA" NUMBER, 
	"LARGURA" NUMBER, 
	"PROFUNDIDADE" NUMBER, 
	"ORDEM" NUMBER, 
	"STATUS" NUMBER, 
	 CONSTRAINT "ENDERECO_TIPO_STATUS_CC" CHECK (status in (0,1)) ENABLE, 
	 CONSTRAINT "ENDERECO_TIPO_ID_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;