CREATE TABLE "WMS"."ENDERECO_RUA" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"RUA" VARCHAR2(3) NOT NULL ENABLE, 
	"EXPEDICAO" NUMBER, 
	"VIRTUAL" NUMBER, 
	"MAX_ATV_ABAST" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "ENDERECO_RUA_EXPEDICAO_CC" CHECK (expedicao in (0,1)) ENABLE, 
	 CONSTRAINT "ENDERECO_RUA_VIRTUAL_CC" CHECK (virtual in (0,1)) ENABLE, 
	 CONSTRAINT "ENDERECO_RUA_ID_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;