CREATE TABLE "WMS"."ERRO_SEPARACAO" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"ATIVIDADE_ID" NUMBER NOT NULL ENABLE, 
	"QTD_ERRO" NUMBER NOT NULL ENABLE, 
	"CREATED" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	"UPDATED" DATE NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	 CONSTRAINT "ERRO_SEPARACAO_ID_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;