CREATE TABLE "WMS"."LOTE" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"CARGA_ID" NUMBER, 
	"PESSOA_ID" NUMBER, 
	"PRIORIDADE" NUMBER, 
	"LOTE" NUMBER, 
	"LS_ID" NUMBER, 
	"LS" VARCHAR2(2), 
	"PESO" NUMBER, 
	"VOLUME" NUMBER, 
	"QTD_ITEM" NUMBER, 
	"QTD_VOLUME" NUMBER, 
	"STATUS" NUMBER DEFAULT ON NULL '0' NOT NULL ENABLE, 
	"SEP_ID" NUMBER, 
	"SEP_START" DATE, 
	"SEP_END" DATE, 
	"CONF_ID" NUMBER, 
	"CONF_START" DATE, 
	"CONF_END" DATE, 
	"CREATED" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	"UPDATED" DATE NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	 CONSTRAINT "LOTE_ID_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "LOTE_CARGA_ID_FK" FOREIGN KEY ("CARGA_ID")
	  REFERENCES "WMS"."CARGA" ("ID") ON DELETE CASCADE ENABLE
   ) ;