CREATE TABLE "WMS"."IMPRESSORA" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NOME" VARCHAR2(4000), 
	"IP" VARCHAR2(4000), 
	"DESCRICAO" VARCHAR2(4000), 
	"CREATED" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	"UPDATED" DATE NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	 CONSTRAINT "IMPRESSORA_ID_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;