CREATE TABLE "WMS"."MOVIMENTACAO_PALETE" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"MOVIMENTACAO_ID" NUMBER, 
	"PALETE_ID" NUMBER, 
	 CONSTRAINT "MOVIMENTACAO_PALET_ID_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "MOVI_PALETE_MOV_FK" FOREIGN KEY ("MOVIMENTACAO_ID")
	  REFERENCES "WMS"."MOVIMENTACAO" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "MOVI_PALET_PALETE_FK" FOREIGN KEY ("PALETE_ID")
	  REFERENCES "WMS"."PALETE" ("ID") ON DELETE CASCADE ENABLE
   ) ;