CREATE TABLE "WMS"."PARAMETRO_ZPL" 
   (	"PADRAOETQ" VARCHAR2(20) NOT NULL ENABLE, 
	"TIPOETIQUETA" VARCHAR2(30) NOT NULL ENABLE, 
	"MODELOIMP" VARCHAR2(10) NOT NULL ENABLE, 
	"ETQLINHA" NUMBER(3,0) NOT NULL ENABLE, 
	"ETQCOLUNA" NUMBER(3,0) NOT NULL ENABLE, 
	"PRECOMANDO" VARCHAR2(40) NOT NULL ENABLE, 
	"COLUNABANCO" VARCHAR2(30) NOT NULL ENABLE, 
	"SUFCOMANDO" VARCHAR2(25), 
	"INDTIPOCOMPLEMENTO" VARCHAR2(1), 
	"QTDCOMPLETACOLUNA" NUMBER(3,0), 
	"TIPCOMANDO" VARCHAR2(1), 
	"NROEMPRESA" NUMBER(3,0), 
	"SEQPARAMETQ" NUMBER(*,0) NOT NULL ENABLE, 
	"SCRIPT" VARCHAR2(250)
   ) ;