CREATE TABLE "WMS"."LINHADESEPARACAO" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"LS" VARCHAR2(2), 
	"NOME" VARCHAR2(4000), 
	"ATACADOVAREJO" VARCHAR2(1), 
	"TIPOSEPAR" VARCHAR2(1), 
	"STATUS" NUMBER, 
	"PESOMAX" NUMBER, 
	"VOLUMEMAX" NUMBER, 
	"MAXATV_ABAST" NUMBER, 
	"CREATED" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	"UPDATED" DATE NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	 CONSTRAINT "LINHADESEPARACAO_ID_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "LINHADESEPARACAO_UNQ_LS" UNIQUE ("LS")
  USING INDEX  ENABLE
   ) ;