CREATE TABLE "WMS"."BOX" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"PRIORIDADE" NUMBER NOT NULL ENABLE, 
	"CREATED" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	"UPDATED" DATE NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	 CONSTRAINT "BOX_ID_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;