CREATE TABLE "WMS"."CARGA_IMPORT" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"STATUS" NUMBER DEFAULT ON NULL '0' NOT NULL ENABLE, 
	"PRIORIDADE" NUMBER, 
	"LOTES" NUMBER, 
	"PESO" NUMBER, 
	"VOLUME" NUMBER, 
	"BOX_ID" NUMBER, 
	"DESTINO" VARCHAR2(4000), 
	"CREATED" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	"UPDATED" DATE NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	"TIPO" VARCHAR2(1), 
	"IMPRESSORA_ID" NUMBER, 
	 CONSTRAINT "CARGA_IMPORT_ID_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;