CREATE TABLE "WMS"."CARGA" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"LOTES" NUMBER, 
	"PRIORIDADE" NUMBER, 
	"BOX_ID" NUMBER, 
	"PESO" NUMBER, 
	"VOLUME" NUMBER, 
	"STATUS" NUMBER DEFAULT ON NULL '0' NOT NULL ENABLE, 
	"DATE_START" DATE, 
	"DATE_END" DATE, 
	"CREATED" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	"UPDATED" DATE NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	"TIPO" VARCHAR2(1), 
	 CONSTRAINT "CARGA_ID_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;