CREATE TABLE "WMS"."PRODUTIVO_BOX" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"PRODUTIVO_ID" NUMBER, 
	"BOX" NUMBER NOT NULL ENABLE, 
	"CREATED" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	"UPDATED" DATE NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	 CONSTRAINT "PRODUTIVO_BOX_ID_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "PRODUTIVO_BOX_PRODUTIVO_ID_FK" FOREIGN KEY ("PRODUTIVO_ID")
	  REFERENCES "WMS"."PRODUTIVO" ("ID") ON DELETE CASCADE ENABLE
   ) ;