CREATE TABLE "WMS"."LOTE_PRINT_LOG" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"CARGA_ID" NUMBER, 
	"LOTE" VARCHAR2(4000), 
	"SEP_ID" NUMBER, 
	"CREATED" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	"UPDATED" DATE NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	 CONSTRAINT "LOTE_PRINT_LOG_ID_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;