CREATE TABLE "WMS"."MOVIMENTACAO_VISUAL" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"ORIGEM_ID" NUMBER NOT NULL ENABLE, 
	"DESTINO_ID" NUMBER NOT NULL ENABLE, 
	"QTD" NUMBER NOT NULL ENABLE, 
	"EMBALAGEM_ID" NUMBER NOT NULL ENABLE, 
	"TIPO" VARCHAR2(4000) NOT NULL ENABLE, 
	"PALETE_ID" NUMBER, 
	"MOVIMENTACAO_ID" NUMBER, 
	"CREATED" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	"UPDATED" DATE NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	 CONSTRAINT "MOVIMENTACAO_VISUA_TIPO_CC" CHECK (tipo in ('A','D','R')) ENABLE, 
	 CONSTRAINT "MOVIMENTACAO_VISUA_ID_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;