CREATE OR REPLACE EDITIONABLE TRIGGER "WMS"."ATIVIDADE_QTD" 
BEFORE 
insert on "ATIVIDADE" 
for each row 
begin 
UPDATE LOTE  
SET QTD_ITEM = NVL(QTD_ITEM,0)+1, 
QTD_VOLUME = NVL(QTD_VOLUME,0)+(:NEW.QTD_PEDIDO/:NEW.QTD_EMB) 
WHERE CARGA_ID = :NEW.CARGA_ID 
AND LOTE = :NEW.LOTE; 
end; 
 

/
ALTER TRIGGER "WMS"."ATIVIDADE_QTD" ENABLE;