CREATE OR REPLACE FORCE EDITIONABLE VIEW "WMS"."V_ENDERECO_EMB_BKP" ("SEQPRODUTO", "QTDEMBALAGEM", "EMBALAGEM", "NROAPARTAMENTO", "NROSALA", "CODRUA", "NROPREDIO") AS 
  SELECT A.PRODUTO_ID as SEQPRODUTO,
       A.QTD_EMB as QTDEMBALAGEM,
       A.EMB as EMBALAGEM,
       MIN(B.APARTAMENTO) AS NROAPARTAMENTO,
       MIN(B.SALA) AS NROSALA,
       MIN(B.RUA) AS CODRUA,
       MIN(B.PREDIO) AS NROPREDIO
  FROM WMS.PRODUTO_EMBALAGEM A
     , WMS.ENDERECO B
     , WMS.LINHADESEPARACAO C
     , WMS.PRODUTO D
 WHERE A.PRODUTO_ID = D.ID
   and A.ID = B.EMBALAGEM_ID
   and C.LS = A.LS
   and B.TERREO = 1
   and B.PULMAO = 0
   AND B.RUA NOT IN ( 'AV','990','995','996','997','998','999')
 group by A.PRODUTO_ID,
       A.QTD_EMB,
       A.EMB
;