CREATE OR REPLACE FORCE EDITIONABLE VIEW "WMS"."V_PRODUTO" ("ID", "NOME", "FORNECEDOR_ID", "REFFABRICANTE") AS 
  SELECT A.SEQPRODUTO   AS ID, 
       A.DESCCOMPLETA AS NOME, 
       WMS.F_FORNECEDOR_AGG(A.SEQPRODUTO) AS FORNECEDOR_ID, 
       A.REFFABRICANTE AS REFFABRICANTE 
  FROM CONSINCO.MLO_PRODUTO A 
 WHERE A.NROEMPRESA = 1 
;