CREATE OR REPLACE FORCE EDITIONABLE VIEW "WMS"."PRODUTO_EMBALAGEM_AV" ("LS", "PRODUTO_ID", "EMB", "QTD_EMB", "PESO_BRUTO", "PESO_LIQUIDO", "ALTURA", "LARGURA", "PROFUNDIDADE", "ATACADOVAREJO") AS 
  select A.LS, 
       A.PRODUTO_ID, 
       A.EMB, 
       A.QTD_EMB, 
       A.PESO_BRUTO, 
       A.PESO_LIQUIDO, 
       A.ALTURA, 
       A.LARGURA, 
       A.PROFUNDIDADE, 
       B.ATACADOVAREJO 
  from WMS.PRODUTO_EMBALAGEM A, 
       WMS.LINHADESEPARACAO B 
 where A.LS = B.LS 
;