CREATE OR REPLACE FORCE EDITIONABLE VIEW "WMS"."VW_ATIVIDADE_CONF" ("CARGA", "SEQLOTE", "CODPROD", "PROD", "PRODFULL", "EMBCODE", "EMB", "LOCAL", "BOX", "CODRUA", "NROPREDIO", "QTDEMBALAGEM", "EMBALAGEM", "QTD_PEDIDO", "SEP_QTD", "CONF_QTD", "PESSOA_ID", "ATIVIDADE_ID") AS 
  SELECT A.CARGA_ID CARGA, 
         A.LOTE SEQLOTE, 
         A.PRODUTO_ID CODPROD, 
         REPLACE(RPAD(SUBSTR(B.DESCCOMPLETA, 1, 25), 25, CHR(32)),'''','') PROD, 
         replace(B.DESCCOMPLETA,'''','') PRODFULL, 
         (SELECT MAX(TO_NUMBER(REGEXP_REPLACE(D.CODACESSO, '[^0-9]+', ''))) 
            FROM CONSINCO.MAP_PRODCODIGO D 
           WHERE D.SEQPRODUTO = A.PRODUTO_ID 
             AND D.QTDEMBALAGEM = G.QTDEMBALAGEM) EMBCODE, 
         G.EMBALAGEM || '-' || G.QTDEMBALAGEM EMB, 
         E.CODRUA || '.' || E.NROPREDIO || '.' || E.NROAPARTAMENTO || '.' || 
         E.NROSALA LOCAL, 
         F.NROBOX BOX, 
         E.CODRUA AS CODRUA, 
         E.NROPREDIO AS NROPREDIO, 
         G.QTDEMBALAGEM, 
         G.EMBALAGEM, 
         A.QTD_PEDIDO, 
         A.SEP_QTD, 
         A.CONF_QTD, 
         A.PESSOA_ID, 
         A.ID AS ATIVIDADE_ID 
    FROM WMS.ATIVIDADE             A, 
         CONSINCO.MAP_PRODUTO      B, 
         CONSINCO.MAP_FAMEMBALAGEM G, 
         WMS.V_ENDERECO_EMB        E, 
         CONSINCO.MLO_CARGAEXPED   F 
   WHERE B.SEQFAMILIA   = G.SEQFAMILIA 
     AND B.SEQPRODUTO   = A.PRODUTO_ID 
     --AND A.EMB          = G.EMBALAGEM 
     AND A.PRODUTO_ID   = B.SEQPRODUTO 
     AND F.NROCARGA     = A.CARGA_ID 
     AND E.SEQPRODUTO = A.PRODUTO_ID 
     AND E.QTDEMBALAGEM = A.QTD_EMB 
     AND A.QTD_EMB = G.QTDEMBALAGEM 
   ORDER BY E.CODRUA, E.NROPREDIO DESC 
;