CREATE OR REPLACE FORCE EDITIONABLE VIEW "WMS"."V_ENDERECO_EMB" ("SEQPRODUTO", "QTDEMBALAGEM", "EMBALAGEM", "NROAPARTAMENTO", "NROSALA", "CODRUA", "NROPREDIO") AS 
  SELECT A.SEQPRODUTO, 
       A.QTDEMBALAGEM, 
       A.EMBALAGEM, 
       MIN(B1.NROAPARTAMENTO) AS NROAPARTAMENTO, 
       MIN(B1.NROSALA) AS NROSALA, 
       MIN(B1.CODRUA) AS CODRUA, 
       MIN(B1.NROPREDIO) AS NROPREDIO 
  FROM CONSINCO.MLO_PRODEMBWM A1 
  , CONSINCO.MLO_ENDERECO B1 
  , CONSINCO.MLO_LINHASEPARPERM C1 
  , consinco.MLO_PRODEMBALAGEM A 
  , WMS.LINHADESEPARACAO C 
 WHERE  A1.SEQPRODUTO = B1.SEQPRODUTO 
   AND B1.SEQENDERECO = C1.SEQENDERECO 
   AND C1.CODLINHASEPAR = A1.CODLINHASEPAR 
   AND B1.ESPECIEENDERECO IN ('M', 'V', 'A') 
   AND C1.CODDISTRIBLINHA in ('N') 
   AND A.SEQPRODUTO = A1.SEQPRODUTO 
   AND A.QTDEMBALAGEM = A1.QTDEMBALAGEM 
   AND A.NROEMPRESA = 1 
   AND B1.INDTERREOAEREO = 'T' 
   AND B1.STATUSENDERECO = 'O' 
   AND B1.CODRUA NOT IN ( 'AV','990','995','996','997','998','999') 
   and C.LS = A1.CODLINHASEPAR 
   and A.STATUSEMBALAGEM = 'A' 
   GROUP BY A.SEQPRODUTO, 
       A.QTDEMBALAGEM, 
       A.EMBALAGEM 
;