CREATE OR REPLACE FORCE EDITIONABLE VIEW "WMS"."V_PULMAO_BOX" ("SEQPRODUTO", "QTDMOVTO", "QTDEMBALAGEM", "EMBALAGEM", "QTD", "NROCARGA") AS 
  SELECT B.SEQPRODUTO, 
       sum(A.QTDMOVTO) QTDMOVTO, 
       B.QTDEMBALAGEM QTDEMBALAGEM, 
       B.EMBALAGEM EMBALAGEM, 
       sum(A.QTDMOVTO)/B.QTDEMBALAGEM QTD, 
       A.NROCARGA 
  from consinco.MLO_ENDERECOMOVTO A, 
       consinco.MLO_PRODEMBALAGEM B 
 where A.TIPMOVTO In ('R', 'M') 
   and A.INDENTRADASAIDA = 'S' 
   and A.NROEMPRESA = 1 
   and NVL(a.INDREPSEPPALINTEIRO, 'N') = 'S' 
   and A.SEQPRODUTO = B.SEQPRODUTO 
   and A.QTDEMBALAGEM = B.QTDEMBALAGEM 
   and A.NROEMPRESA = B.NROEMPRESA 
 group by B.SEQPRODUTO, 
          B.QTDEMBALAGEM, 
          B.EMBALAGEM, 
          A.NROCARGA 
 order by 1, 3 
;