CREATE OR REPLACE FORCE EDITIONABLE VIEW "WMS"."V_PRODUTO_EMBALAGEM" ("PRODUTO_ID", "EMB", "QTD_EMB", "PESO_BRUTO", "PESO_LIQUIDO", "ALTURA", "LARGURA", "PROFUNDIDADE") AS 
  SELECT A.SEQPRODUTO   AS PRODUTO_ID, 
       C.EMBALAGEM    AS EMB, 
       C.QTDEMBALAGEM AS QTD_EMB, 
       C.PESOBRUTO    AS PESO_BRUTO, 
       C.PESOLIQUIDO  AS PESO_LIQUIDO, 
       C.ALTURA       AS ALTURA, 
       C.LARGURA      AS LARGURA, 
       C.PROFUNDIDADE AS PROFUNDIDADE 
  FROM CONSINCO.MRL_PRODUTOEMPRESA A 
 INNER JOIN CONSINCO.MAP_PRODUTO B 
    ON B.SEQPRODUTO = A.SEQPRODUTO 
 INNER JOIN CONSINCO.MAP_FAMEMBALAGEM C 
    ON C.SEQFAMILIA = B.SEQFAMILIA 
 INNER JOIN CONSINCO.MAD_PARAMETRO D 
    ON D.NROEMPRESA = A.NROEMPRESA 
   AND D.INDINTMAXWM IN ('S', 'C') 
 INNER JOIN CONSINCO.MRL_FAMEMBEMPRESA E 
    ON E.SEQFAMILIA = C.SEQFAMILIA 
   AND E.QTDEMBALAGEM = C.QTDEMBALAGEM 
   AND E.NROEMPRESA = D.NROEMPRESA 
;