CREATE OR REPLACE FORCE EDITIONABLE VIEW "WMS"."VW_ZPL_PRINT" ("LINHA", "CONTROLEETQ", "SEQLOTE", "NROEMPRESA", "SEQPESSOA", "CIDADE", "UF", "NROPALETE", "NOMEROTA", "SEQUENCIACLIENTE", "TIPEMBALADO", "SEQPALETE", "NROBOX", "NROETQLOTESEPAR", "NROSEQLOTE", "QTDETIQUETA", "PRODUTIVO", "NROQUEBRA", "NROCARGA", "CODDEPOSSEPAR", "CODLINHASEPAR", "DESCLINHASEPAR", "DESTINO", "DTAHORGERACAO", "TARJA", "ETIQUETA", "ORDERBY_1", "LINHASEPAR") AS 
  Select A.LOTE AS LINHA, 
       A.LOTE AS CONTROLEETQ, 
       A.LOTE AS SEQLOTE, 
       1 AS NROEMPRESA, 
       case when A.PESSOA_ID = 0 then 'BLOCADO' else C.SEQPESSOA||'-'||C.NOMERAZAO end AS SEQPESSOA, 
       NULL AS CIDADE, 
       NULL AS UF, 
       0 AS NROPALETE, 
       '.' as NOMEROTA, 
       NULL AS SEQUENCIACLIENTE, 
       NULL TIPEMBALADO, 
       0 AS SEQPALETE, 
       D.BOX_ID AS NROBOX, 
       A.ID AS NROETQLOTESEPAR, 
       0 AS NROSEQLOTE, 
       0 AS QTDETIQUETA, 
       NULL AS PRODUTIVO, 
       0 AS NROQUEBRA, 
       A.CARGA_ID AS NROCARGA, 
       '01' AS CODDEPOSSEPAR, 
       A.LS_ID AS CODLINHASEPAR, 
       B.NOME AS DESCLINHASEPAR, 
       D.DESTINO, 
       D.CREATED AS DTAHORGERACAO, 
       '' AS TARJA, 
       A.LOTE AS ETIQUETA, 
       B.NOME AS ORDERBY_1, 
       B.NOME AS LINHASEPAR 
  From WMS.LOTE A 
  INNER JOIN WMS.LINHADESEPARACAO B ON A.LS = B.LS  
  LEFT JOIN consinco.GE_PESSOA C ON A.PESSOA_ID =  C.SEQPESSOA  
  INNER JOIN WMS.CARGA_IMPORT D ON  A.CARGA_ID = D.ID 
;